site_name: David K. Hays
site_url: https://davidkhays.com
plugins: []
watch:
  - overrides
extra_css:
  - assets/stylesheets/extra.css
extra_javascript:
  - assets/javascripts/extra.js
extra:
  generator: false
theme:
  name: material
  custom_dir: overrides
  font: false
  favicon: assets/images/favicon.png
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
nav:
  - Home: index.md
  - About: about.md
  - Gallery: gallery.md
  - EPILOGUE: epilogue/index.md
  - OFF-SYLLABUS: off-syllabus/index.md
  - Store: store.md